version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "8082:3306"
    environment:
      MYSQL_DATABASE: javadb
      MYSQL_USER: javauser
      MYSQL_PASSWORD: javapass
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  db: