server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:8082/javadb
    username: javauser
    password: javapass
  jpa:
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create